# Generated by Django 6.0.3 on 2026-03-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventoryitem",
            name="unit_price",
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
