"""
Django settings for ims_backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Treat non-debug mode as production-like for security defaults.
IS_PRODUCTION = not DEBUG

ALLOWED_HOSTS = ['127.0.0.1', '0.0.0.0:8000', 'localhost']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps for API support
    "rest_framework",  # authentication and API building
    "corsheaders",
    # Local apps
    "accounts",
    "inventory",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Custom middleware to log requests and add API-centric headers
    "accounts.middleware.RequestLoggingMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    
]

ROOT_URLCONF = "ims_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ims_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "localhost")
POSTGRES_PORT = os.getenv("POSTGRES_PORT", "5432")

# Dedicated credentials for Django test database operations.
# Defaults align with your requested testing role: test_user / test.
POSTGRES_TEST_USER = os.getenv("POSTGRES_TEST_USER", "test_user")
POSTGRES_TEST_PASSWORD = os.getenv("POSTGRES_TEST_PASSWORD", "test")

# Ensure test commands connect with the dedicated testing database role.
if "test" in sys.argv:
    POSTGRES_USER = POSTGRES_TEST_USER
    POSTGRES_PASSWORD = POSTGRES_TEST_PASSWORD

if not (POSTGRES_DB and POSTGRES_USER and POSTGRES_PASSWORD):
    raise RuntimeError(
        "PostgreSQL configuration is required. "
        "Set POSTGRES_DB, POSTGRES_USER, and POSTGRES_PASSWORD in your environment."
    )

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": POSTGRES_DB,
        "USER": POSTGRES_USER,
        "PASSWORD": POSTGRES_PASSWORD,
        "HOST": POSTGRES_HOST,
        "PORT": POSTGRES_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

CORS_ALLOW_ALL_ORIGINS = True  # later restrict this in production
CORS_ALLOW_HEADERS = ['*']
CORS_ALLOW_METHODS = ['*']

# Cookie and browser security hardening.
# 'Secure' ensures cookies are only sent over HTTPS in production.
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION

# 'HttpOnly' prevents JavaScript access to the session cookie.
SESSION_COOKIE_HTTPONLY = True

# 'Lax' allows normal navigation while reducing CSRF attack surface.
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Keep CSRF token readable by browser scripts/forms when needed.
CSRF_COOKIE_HTTPONLY = False

# Use host-prefixed cookie names in production to reduce cookie fixation risk.
SESSION_COOKIE_NAME = "__Host-sessionid" if IS_PRODUCTION else "sessionid"
CSRF_COOKIE_NAME = "__Host-csrftoken" if IS_PRODUCTION else "csrftoken"

# Restrict cookie scope and session lifetime.
SESSION_COOKIE_PATH = "/"
CSRF_COOKIE_PATH = "/"
SESSION_COOKIE_AGE = 60 * 60  # 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

# Enforce HTTPS redirects and secure transport options in production.
SECURE_SSL_REDIRECT = IS_PRODUCTION
SECURE_HSTS_SECONDS = 31536000 if IS_PRODUCTION else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = IS_PRODUCTION
SECURE_HSTS_PRELOAD = IS_PRODUCTION

# Prevent MIME-type sniffing and framing-based clickjacking.
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    # ---------------------------------------------------------------------------
    # Global rate-limiting defaults applied to every endpoint.
    # AnonRateThrottle keys by IP; UserRateThrottle keys by authenticated user.
    # Sensitive endpoints override these via ScopedRateThrottle (see throttles.py).
    # ---------------------------------------------------------------------------
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",   # unauthenticated requests
        "rest_framework.throttling.UserRateThrottle",   # authenticated requests
    ],
    "DEFAULT_THROTTLE_RATES": {
        # --- Global baselines ---
        "anon": "100/hour",           # anonymous users across all endpoints
        "user": "1000/hour",          # authenticated users across all endpoints
        # --- Auth endpoints (scoped, stricter) ---
        "login": "5/minute",          # brute-force login protection
        "register": "10/hour",        # prevent automated account-creation spam
        "password_reset": "5/hour",   # prevent email flooding / OTP enumeration
        "token_refresh": "30/minute", # prevent token farming
        # --- Inventory write operations ---
        "inventory_write": "60/hour", # create / update / delete on inventory items
        # --- Authenticated profile endpoint ---
        "profile": "120/hour",        # throttle /api/auth/me/ access
    },
}


# Email / notification settings (used by notifications/email_service.py)
SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "webmaster@localhost")
ADMIN_PANEL_URL = os.getenv(
    "ADMIN_PANEL_URL", "http://localhost:8000/admin/inventory/inventoryitem/"
)
PASSWORD_RESET_CODE_EXPIRY_MINUTES = int(
    os.getenv("PASSWORD_RESET_CODE_EXPIRY_MINUTES", "10")
)


AUTH_USER_MODEL = "accounts.User"

